name: Bump version on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    name: Unit Tests
    uses: ./.github/workflows/test-unit.yml

  bump:
    needs: test
    uses: MaxiGarcia13/gh-actions/.github/workflows/bump-version.yml@main

  publish:
    needs: bump
    uses: MaxiGarcia13/gh-actions/.github/workflows/npm-publish.yml@main
    secrets: inherit
    with:
      command: publish:npm
